### ISSUE TITLE
Wrong 4pin crystal pin numbering

### ISSUE THREAD

**Issue by diggit** [KiCad/Crystals.pretty#17]
All SMD 4pin crystal foorpotints except 0603 and 2016 have wrong pin numbers 1,2,3,3 instead 1,2,3,4.

*Sorry guys, not time to fix this from my side. Even though it is quite simple.*

**Comment by SchrodingersGat** [comment]
Before changing anything we need to ensure that the pin numbering for the crystal symbols matches. The 1,2,3,3 numbering is a legacy thing relating to old schematic symbol

**Comment by diggit** [comment]
Yes, it is legacy from old Crystal_SMD symbol which had only 3 pins.

Most 4 pin SMD crystals have crystal on pads 1,3(diagonal) and pads 2,4 are unused (in device.lib shown as grounds, there is another one variant). I don't know about any collision.

**Comment by SchrodingersGat** [comment]
Fix issued
